apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-volume
  namespace: statfive
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mariadb"
