apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-volume
  namespace: statfive
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/etc/letsencrypt"
