apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-claim
  namespace: statfive
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
