version: '3'


networks:
  statfive-network:


volumes:
  mariadb_data:
  video:


services:
  mariadb:
    image: mariadb
    tty: true
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: statfive
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: statfive_user
      MYSQL_PASSWORD: statfive_password
    networks:
      - statfive-network
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    depends_on:
      - mariadb
    ports:
      - 80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root 
    networks:
      - statfive-network
    restart: always

  api:
    build: ./API
    links:
      - mariadb
      - tracker
    depends_on:
      - mariadb
    ports:
      - 5000
    networks:
      - statfive-network
    environment:
      - PYTHONUNBUFFERED=0
      - MYSQL_DATABASE=statfive
      - MYSQL_USER=statfive_user
      - MYSQL_PASSWORD=statfive_password
      - MYSQL_HOST=db
      - PROD=docker
    volumes:
      - video:/app/video
    restart: always

  tracker:
     build: ./tracker
     ports:
       - 8000
     networks:
       - statfive-network
     volumes:
       - video:/app/video
     restart: always

  dashboard:
    build: ./Dashboard
    command: npm run dev
    volumes:
      - ./Dashboard:/app
      - /app/node_modules
    ports:
      - 3000
    networks:
      - statfive-network
    depends_on:
      - mariadb
      - api

  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      - statfive-network
    links:
      - dashboard
      - api
    depends_on:
      - dashboard
      - api
