{
 "title": "Kubernetes Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kubelet_runtime_operations_total{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\"}, instance)"
    }
   },
   {
    "name": "instance_api",
    "query": {
     "query": "label_values(apiserver_request_total{job=\"apiserver\", cluster=\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "K8S Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kube_node_labels", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 19, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kube_namespace_labels", "legendFormat": "{{namespace}}" }
   ]
  },
  {
   "title": "Persistent Volumes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kube_persistentvolume_labels", "legendFormat": "{{persistentvolume}}" }
   ]
  },
  {
   "title": "Persistent Volumes Claims",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_labels",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "sum(kube_service_labels)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "sum(kube_deployment_labels)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "sum(kube_pod_labels)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Secrets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "sum(kube_secret_labels)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Replicasets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "sum(kube_replicaset_labels)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Daemonsets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "sum(kube_daemonset_labels)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "kube_service_labels" }
   ]
  },
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "kube_deployment_labels" }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kube_pod_container_status_running"
    }
   ]
  },
  {
   "title": "Replicasets",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    { "expr": "kube_replicaset_labels" }
   ]
  },
  {
   "title": "Headlines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{resource=\"cpu\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"$cluster\", resource=\"cpu\"}) / sum(kube_node_status_allocatable{resource=\"cpu\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{resource=\"memory\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"$cluster\", resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage VM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}) by (node)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU usage Kubelet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=\"$cluster\",job=\"kubelet\", metrics_path=\"/metrics\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage KubernetesAPI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"apiserver\",instance=~\"$instance_api\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_owner{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_limits{cluster=\"$cluster\", resource=\"cpu\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage VM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!=\"\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage Kubelet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=\"$cluster\",job=\"kubelet\", metrics_path=\"/metrics\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage KubernetesAPI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"apiserver\",instance=~\"$instance_api\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests by Namespace",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_owner{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"memory\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"memory\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"$cluster\", resource=\"memory\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits{cluster=\"$cluster\", resource=\"memory\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Container Bandwidth by VM: Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by VM: Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Rate of Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Rate of Packets Dropped",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}