apiVersion: v1
kind: Service
metadata:
  labels:
    app: statfive
  name: mariadb
  namespace: statfive
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: statfive
    tier: mariadb
