apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-volume
  namespace: statfive
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: statfive
    shareName: statfive-api-share
    readOnly: false
