apiVersion: v1
kind: PersistentVolume
metadata:
  name: letsencrypt-volume
  namespace: statfive
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: statfive
    shareName: statfive-letsencrypt-share
    readOnly: false
