apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-volume
  namespace: statfive
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: statfive
    shareName: statfive-api-share
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-claim
  namespace: statfive
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: statfive
  name: api
  namespace: statfive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statfive
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: statfive
        tier: backend
    spec:
      containers:
        - image: "acalhabi/statfive_api"
          name: api
          env:
            - name: PYTHONBUFFERED
              value: "0"
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_DATABASE
              value: "statfive"
            - name: PROD
              value: "kubernetes"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: URL_WEB
              value: "https://dashboard.statfive.fr/"
            - name: API_URL
              value: "https://api.statfive.fr"            
            - name: MAIL_USERNAME
              value: "noreply@statfive.fr"
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/app/video"
              name: api-storage
      volumes:
        - name: api-storage
          persistentVolumeClaim:
            claimName: api-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: statfive
  name: api
  namespace: statfive
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: statfive
    tier: backend
