apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: statfive
  name: phpmyadmin
  namespace: statfive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statfive
      tier: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: statfive
        tier: phpmyadmin
    spec:
      containers:
        - image: phpmyadmin/phpmyadmin
          name: phpmyadmin
          env:
            - name: PMA_HOST
              value: mariadb
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: root_password
          ports:
            - containerPort: 80
