apiVersion: v1
kind: Service
metadata:
  labels:
    app: statfive
  name: api
  namespace: statfive
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: statfive
    tier: backend
