apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim
  namespace: statfive
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
